#configure how much armor does against damage. Valid values are 'armor', 'damage', and 'toughness'. Set to "damage" to not modify damage at this step.
"first damage reduction formula" = "(damage / MAX(0.05, 1 + (toughness+armor) * 0.05)) * MIN(1.0, damage*damage/MAX(0.1, armor)) - MAX(0.0, MIN(armor*0.2, (damage - armor * 0.9) * 0.025 * toughness))"
#configure sudden death protection for armor toughness. Valid values are 'armor', 'damage', and 'toughness'. Set to "damage" to not modify damage at this step.
"second damage reduction formula" = "MAX(0, damage - toughness / 8)"
#configure the efficiency of protection enchantments. Valid values are 'enchant' and 'damage'. Set to "damage" to not modify damage at this step.
"enchantment damage reduction formula" = "damage*10/(10+enchant*2)"
#configure how armor degrades. Valid values are 'remaining' and 'max'. Set to 1 to disable.
"armor degradation formula" = "1"
#Set to false to only cause the armor value to degrade. This will leave extra attributes such as toughness untouched. If using Project: War Dance, stealth will not degrade regardless of damage.
"universal armor degradation" = false

