#Whether search for recipes asynchronously.
asyncRecipeSearching = false
#Whether use vbo for preview page rendering.
useVBO = false
#Duration of the multiblock in-world preview (s)
#Range: 1 ~ 999
multiblockPreviewDuration = 10
#Duration of the multiblock in-world pattern error position (s)
#Range: 1 ~ 999
multiblockPatternErrorPosDuration = 10

